on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksctreg.azurecr.io
        username: ${{ secrets.acr_aksctreg_username }}
        password: ${{ secrets.acr_aksctreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aksctreg.azurecr.io/ndiaksminitest:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aksctreg.azurecr.io/ndiaksminitest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ndiaksminitest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ndi-aks-mini-test1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ndi-aks-mini-test1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ndi-aks-mini-test1
        container-registry-url: aksctreg.azurecr.io
        container-registry-username: ${{ secrets.acr_aksctreg_username }}
        container-registry-password: ${{ secrets.acr_aksctreg_password }}
        secret-name: ndiaksminitedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ndi-aks-mini-test1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          aksctreg.azurecr.io/ndiaksminitest:${{ github.sha }}
        imagepullsecrets: |
          ndiaksminitedockerauth
